# Generated by Django 4.2.4 on 2023-08-26 11:06

from django.db import migrations




class Migration(migrations.Migration):
    
    dependencies = [
        ('authentication', '0005_auto_20230826_1353'),
    ]

    operations = [
    ]
